- promise_types/git/README.md
- promise_types/git/git.py
Running the following promise with the original code will lead to errors.
```cfengine3
bundle agent main
{
git:
"cxxvector"
repository => "git@github.com:KotzaBoss/CXXVector.git",
destination => "/tmp/CXXVector",
ssh_options => "-i /home/__alias__/.ssh/id_rsa",
version => "master";
}
```
By putting a simple logging after setting up the environment:
```python
def _git_envvars(self, model: object):
...
self.log_critical(env)
return env
```
we see the `GIT_SSH_COMMAND` environment variable is set to the problematic value:
```
CRITICAL: { ..., 'GIT_SSH_COMMAND': 'git -i /home/__alias__/.ssh/id_rsa'}
```
The change introduces a new attribute `ssh_executable` which defaults to `'ssh'`
solving this error and allowing valid customisation of the ssh command.
Ticket: None
Changelog: None
> Fixed environment variable logic and added ssh_executable attribute

- promise_types/ansible/ansible_promise.py
Testing was done by running the example.cf with python3.5 interpreter
Ticket: CFE-3729
> CFE-3729: Refactored ansible custom promise to be Python 3.5 compatible

- libraries/python/cfengine.py
`create_attribute_object` now calls `create_attribute_dict` to
to get the dictionary necessary to instantiate an attribute object
Ticket: None
> Extracted attribute dictionary creation into separate method

- libraries/python/cfengine.py
The `__repr__` magic method can ease debugging by allowing pretty printing of
the object itself instead of fiddling with individual attributes.
```python
>>> print(attr_obj)
AttributeObject(attr1='some_value', attr2=1)
```
Ticket: None
> Added `__repr__` to `AttributeObject`

- promise_types/iptables/iptables.py
- promise_types/iptables/test.cf
Testing of the module was done as follows:
```shell
iptables -F
for _ in {1..3}; do
iptables -A INPUT -j ACCEPT
iptables -A OUTPUT -j ACCEPT
done
iptables -L
#Chain INPUT (policy ACCEPT)
#target     prot opt source               destination
#ACCEPT     all  --  anywhere             anywhere
#ACCEPT     all  --  anywhere             anywhere
#ACCEPT     all  --  anywhere             anywhere
#
#Chain FORWARD (policy ACCEPT)
#target     prot opt source               destination
#
#Chain OUTPUT (policy ACCEPT)
#target     prot opt source               destination
#ACCEPT     all  --  anywhere             anywhere
#ACCEPT     all  --  anywhere             anywhere
#ACCEPT     all  --  anywhere             anywhere
```
By commenting out the other test bundles except `all_flushed` bundle: …
> ENT-7423: Added implementation for iptables custom promise `flush` command

- promise-types/http/README.org
- promise-types/http/http_promise_type.py
Merge together: https://github.com/cfengine/build-index/pull/287
- Inverted logic for downloading files over 512KiB.
- Implemented use of temporary file to prevent partial written file from being used.
- Parent directories leading to promised file are now created automatically.
- Stopped returning REPAIRED when no changes to file were made (now returns KEPT).
- Fixed typo.
> ENT-9047: Various improvements to http promise type

- security/delete-home-dotshosts/policy/main.cf
Parser doesn't like the dots and colons otherwise.
> delete-home-dotshosts: Added quotes for isvariable() arguments

- libraries/bash/cfengine.sh
Just set `response_classes` variable, in addition to `response_result`.
From this PR: https://github.com/cfengine/masterfiles/pull/2547 by @basvandervlies
> Added an option to set classes in bash library

- security/enable-aslr/README.md
- security/uninstall-apache/README.md
- security/uninstall-apache/uninstall-apache.cf
- security/uninstall-bind/README.md
- security/uninstall-bind/uninstall-bind.cf
- security/uninstall-dhcp/README.md
- security/uninstall-dhcp/uninstall-dhcp.cf
- security/uninstall-dovecot/README.md
- security/uninstall-dovecot/uninstall-dovecot.cf
- security/uninstall-rsh-server/README.md
- security/uninstall-samba/README.md
- security/uninstall-samba/uninstall-samba.cf
- security/uninstall-squid/README.md
- security/uninstall-squid/uninstall-squid.cf
- security/uninstall-talk/README.md
- security/uninstall-xinetd/README.md
- security/uninstall-xinetd/uninstall-xinetd.cf
- Added 'uninstall-apache' module
- Added 'uninstall-dhcp' module
- Added 'uninstall-bind' module
- Added 'uninstall-dovecot' module
- Added 'uninstall-samba' module
- Added 'uninstall-squid' module
- Added 'uninstall-xinetd' module
- Small README improvements for enable-aslr, uninstall-rsh-server and uninstall-talk
> Added 7 uninstall modules

- security/uninstall-bind/README.md
- security/uninstall-bind/uninstall-bind.cf
According to the OpenSCAP guide, it should be named bind. However on
my Ubuntu machine, it is called bind9. Better remove both then.
> Added another name for bind package in apt

- examples/git-using-lib/git_using_lib.py
- examples/gpg/gpg.py
- examples/rss/rss.py
- examples/site-up/site_up.py
- libraries/python/README.org
- libraries/python/cfengine.py
- promise-types/ansible/ansible_promise.py
- promise-types/groups/groups.py
- promise-types/http/http_promise_type.py
- promise-types/iptables/iptables.py
We need to be able to pass meta data about the promise to
validation and evaluation functions. For now, only promise type
is passed, but this shall be extended in the future.
Also, add a simple README.
> Add a 'meta' attribute to validate/evaluate_promise

- cfbs.json
- security/conditional-installer/main.cf
The policy looks for these variables in conditional_installer:main, not
conditional_installer:conditional_installer.
Ticket: ENT-10745
Changelog: Title
> ENT-10745: Fixed bundle name for conditional_installer input data

- cfbs.json
- management/autorun-bundles/README.md
- management/autorun-bundles/def.json
- management/autorun-inputs/README.md
- management/autorun-inputs/def.json
This simply mirrors the existing autorun bundle, but enables inputs and bundles
independently. This is useful in the context of migrating a policy set where you
have a mix of autorun policy that is present in services/autorun as well as
outside that directory.
This enables you to add your custom policy file tagged for autorun outside
services/autorun and have it depend on autorun-bundles.
> Added modules for autorun-inputs and autorun-bundles

- examples/git-using-lib/git_using_lib.py
- examples/gpg/gpg.py
- examples/rss/rss.py
- examples/site-up/site_up.py
- libraries/python/README.md
- libraries/python/README.org
- libraries/python/cfengine.py
- promise-types/ansible/README.md
- promise-types/ansible/ansible_promise.py
- promise-types/git/README.md
- promise-types/git/git.py
- promise-types/groups/README.md
- promise-types/groups/groups.py
- promise-types/http/README.org
- promise-types/http/http_promise_type.py
- promise-types/iptables/README.md
- promise-types/iptables/iptables.py
- promise-types/systemd/README.md
- promise-types/systemd/systemd.py
- Python promise modules: Renamed meta parameter to metadata
- Cleaned up README files relating to the updated promise types
- iptables.py: Autoformatting by black
- Bumped version numbers of to be released modules inside python source code
> Renamed meta to metadata and other cleanups

- examples/gpg/password-store-sync.cf
- examples/site-up/site_up.py
- Fixed repo vs repository attribute in gpg example promise type
- Renamed url parameter to promiser for consistency
> Small consistency fixes to examples

- cfbs.json
- management/disable-recommendations/README.md
- management/disable-recommendations/def.json
Ticket: ENT-11525
Changelog: Title
You can test this by adding my fork at the commit of the latest change, e.g.:
```
cfbs add https://github.com/nickanderson/modules@09b0a68d6cc16190f348878284a83bcfcddfffc0 disable-recommendations
```
Do we want this? I dunno, maybe it's better as a suggestion in MP rather than being a module. But we have other similar modules and I was just looking to improve quality of life for Vrata.
> ENT-11525: Added module to disable recommendations from the MPF

- libraries/python/cfengine.py
These messages inform about changes being done for repaired
promises or errors reported for failed promises, etc. and the
agent requires some whenever there's repaired/failed promise by
a custom promise type module.
Ticket: CFE-4406
Changelog: None
> Always send important log messages from Python-based promise types 

- promise-types/git/git.py
closes https://github.com/cfengine/modules/issues/99
> git promise type must just continue if we have unicode error

- promise-types/git/git.py
TODO: We are not able to keep these version numbers in sync, I think
we should add some "macro" like @@BUILD_INSERT_MODULE_VERSION@@;
https://northerntech.atlassian.net/browse/CFE-4437
> promise-type-python: Prepared for 0.2.5 release

- cfbs.json
- management/package-method-winget/README.md
- management/package-method-winget/install-winget-cli.ps1
- management/package-method-winget/install-winget.ps1
- management/package-method-winget/package-method-winget.cf
- management/package-method-winget/winget-installed.cf
- management/powershell-execution-policy/README.md
- management/powershell-execution-policy/powershell-execution-policy.cf
> Added package-module-winget and needed dependency powershell-execution-policy

- promise-types/git/README.md
- promise-types/git/git.py
There was an issue where due to the lack of the $HOME env var the git commands were not picking up my .gitconfig and .git-credentials files.
This change enables a way to setup authentication for private repositories.
.gitconfig could be:
[credential]
helper = store
and .git-credentials could be something of the form:
https://<url-encoded-username>:<password>@gitlab.com
> Added setting of HOME environment variable for git promise type

- cfbs.json
- inventory/inventory-windows-services.cf
Companion to inventory-systemd for Windows.
Ticket: ENT-12537
> Added inventory-windows-services module

- software/windows/windows-openssh-server.cf
This caused openssh server to never be installed.
> Fixed wrong bundle name in windows-openssh-server module
